sudo: required
language: node_js
node_js:
  - "6.10"
services:
  - docker
before_install:
    - docker build -t $TRAVIS_REPO_SLUG .
install: true
test: true
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $TRAVIS_REPO_SLUG:latest;
    fi
